#!/usr/bin/env bash
 
# Disable BT on local machine and enable it on remote machine, so KB/Mouse reconnect to remote machine.


user=$1
host=$2

#ensure local bluetooth is off
blueutil off
 
#enable imac bluetooth
ssh $user@$host '/usr/local/bin/blueutil on'